### ISSUE TITLE
test_tokens is missing

### ISSUE THREAD

**Issue by marty331** [tonybaloney/cpython-book-samples#5]
I purchased the paperback and it references a file called test_tokens.py, however I don't see it in this repo.  Could you please add it?

**Comment by marty331** [comment]
Found it, sorry for the confusion.

**Comment by jugmac00** [comment]
Hi @marty331,

if you are on Linux or Mac, you can always use `find` to search for a file, e.g. 

```
❯ find -name test_tokens.py
./13/test_tokens.py
```

Or just use the operating system's file explorer.

Btw, back then, when the PDF version was released, I tried and tested every single code example, so all of them should work!

Have fun with this great book!

**Comment by marty331** [comment]
Thanks @jugmac00 I started the book working on my M1 MacBook Pro but quickly switched to a Linux machine that I have in a closet.  The book is great, I'm learning a lot and really glad I purchased it.
